### ISSUE TITLE
Xib

### ISSUE THREAD

**Issue by mimmo00** [cwRichardKim/TinderSimpleSwipeCards#13]
Hi, there is a way to use xib as card?

I tried this:

//instead of: initWithFrame
- (id)initWithCoder:(NSCoder*)coder
{
    if ((self = [super initWithCoder:coder])) {

[self setupView];
...
[self addSubview:overlayView];

}
    return self;
}

//and
-(DraggableView *)createDraggableViewWithDataAtIndex:(NSInteger)index
{
DraggableView *draggableView = [[[NSBundle mainBundle] loadNibNamed:@"cardView" owner:self options:nil] objectAtIndex:0];

    draggableView.information.text = [[[dataObjectsArray objectAtIndex:index] objectForKey:@"item"] objectForKey:@"title"]; //%%% placeholder for card-specific information
    draggableView.delegate = self;
    
    
    return draggableView;
}

but don't work

Thanks

**Comment by clsource** [comment]
I used a storyboard with a UIViewController and assigned the card class to its view.
Then Instantiated 
 ```
UIViewController * controller = [self.storyboard instantiateViewControllerWithIdentifier:@"CardController"];

 CardView * card = (CardView *) controller.view;
```
