### ISSUE TITLE
Which array do i load data to from e.g. Parse?

### ISSUE THREAD

**Issue by danieldelouya** [cwRichardKim/TinderSimpleSwipeCards#16]
I wanna display images in the cards, so which array is that looks for data? 
I'm pretty new to Swift, so it's a little confusing.

**Comment by cwRichardKim** [comment]
Currently, the only information on the cards are the little bits of placeholder text.  I add the UITextLabel to the DraggableView, and then set the content in the DraggableBackgroundView.  Images use the same concept.  Set a blank UIImageView in the DraggableView, and place is properly, and then fill it with content in the backgroundView.

**Comment by niveshchauhan** [comment]
also have the same query regarding uiimage and uilabels with parse data and if not then remove draggbleview Background.

**Comment by cwRichardKim** [comment]
Find where I implemented the text label.  I placed the text label on the card, and made the text label get information from an array.  If you want to pull information from parse, pull it into an array and use that array as the datasource for the image.  You can alternatively put a uiimageview on the card and have each card pull from parse on load, but I wouldn't recommend that as it might clog up the main thread and cause stuttering
