### ISSUE TITLE
Card instantiated from xib doesn't seem to keep subviews within boundaries.

### ISSUE THREAD

**Issue by CharlesW95** [cwRichardKim/TinderSimpleSwipeCards#21]
<img width="311" alt="screen shot 2015-12-27 at 11 06 34 am" src="https://cloud.githubusercontent.com/assets/12402728/12008694/fe683168-ac89-11e5-8983-0c35cdd9de85.png">

This is a subclass of DraggableView, and it holds an ImageView and a UIView (the gray part). When I swipe on the card the UIView seems to poke out the side of the card. I was wondering if this is an intended behavior, or if there is some sort of fix. 

Also, the corner radius property doesn't seem to apply to the bottom of the card.

Thanks!

**Comment by sajayshah** [comment]
You're going to have to programmatically set the cornerRadius for the gray UIView part. I'm also having the same issue with loading from xib.

**Comment by cwRichardKim** [comment]
It probably has to do with masking (sorry for the super late response).  Masks can't be applied while there are shadows because it will mask the shadow as well.  What you can do is put a view ontop of that view with the same dimensions and use that as a mask
