### ISSUE TITLE
Reload card set?

### ISSUE THREAD

**Issue by Alifar** [cwRichardKim/TinderSimpleSwipeCards#26]
What is the best way to reload the card set?

**Comment by aiyub007** [comment]
same issue

**Comment by cwRichardKim** [comment]
from where? from a server or locally?  If it's from a server, have a request send to the server when the number of cards left in the array is less than a certain number, and append those to the end of the array.  This really depends on how you're using the repository, sorry I can't give any more specific information without knowing more about your code
