### ISSUE TITLE
How to delete old card and add new cards

### ISSUE THREAD

**Issue by arishanapalli** [cwRichardKim/TinderSimpleSwipeCards#27]
Hi
TinderSimpleSwipe Cards is awasome one.

I want to delete old cards which are already added to my draggaableView.
on services call i got 5 new cards now i want to remove old cards and added this five news cards.
Is there any best way to do this, please let me know.  Your feedback is appreciated.

**Comment by cwRichardKim** [comment]
remove from where?  from your server or from the user's device?  You can delete data from whatever array you're using as your datasource.  For example, if you're using examplelabels, you can use [remove object](http://stackoverflow.com/questions/19107905/removing-an-item-from-an-array-in-objective-c), or change the datalabel to be mutable (i think it might already be mutable?).  until further clarification, i'm going to close this issue
