### ISSUE TITLE
button Action on the Card is not working 

### ISSUE THREAD

**Issue by arishanapalli** [cwRichardKim/TinderSimpleSwipeCards#28]
Hi 
Team,

I added DraggableView a UIButton i have loaded 10 cards. 
Now each DraggableView have that button.
But on button action its now working 

  [[draggableView btn_welcome] addTarget:self action:@selector(welcomeAction:) forControlEvents:UIControlEventTouchUpInside];
// Button Action Method.
-(void) welcomeAction:(UIButton *)sender{
NSLog(@"Welcome Action invoked");
}

This action is not at all invoked 
Your feedback is highly appricatable.

**Comment by cwRichardKim** [comment]
Where is the function? If it's in the controller, the view will have to have a pointer to the controller, which is bad design and may result in a retain cycle. You want to either use nsnotification or a delegate pattern. This is not an issue with this library so I am closing it
