### ISSUE TITLE
create dynamic cards

### ISSUE THREAD

**Issue by niveshchauhan** [cwRichardKim/TinderSimpleSwipeCards#29]
i wanna display a number of cards based on my Json array .working from 2 days on it i still not getting can u please explain me how can i populate examplecards Array or allCards Array with my json array that is in my ViewController.how can i acheive this.?

**Comment by cwRichardKim** [comment]
answered this here: https://github.com/cwRichardKim/TinderSimpleSwipeCards/issues/16
and longer answer here: https://github.com/cwRichardKim/TinderSimpleSwipeCards/issues/11
