### ISSUE TITLE
How can I tap on the card to move to another view Controller 

### ISSUE THREAD

**Issue by niveshchauhan** [cwRichardKim/TinderSimpleSwipeCards#30]
TapGesture applied like Pan Gesture But delegate not calling in view Controller ,is there any other way to achieve this.

**Comment by cwRichardKim** [comment]
this isn't a problem with this repository, so I'm going to close this issue.  I would recommend looking into how navigation and segues work in iOS.  You can't just call a view controller to show up in a view, you need a parent view controller or navigation controller

**Comment by niveshchauhan** [comment]
I have already created a Parent View Controller inside which i have called
DraggableViewBackground ,Now i need to apply Tap on the card when i create
a protocol in draggableView.h and called it into parent View controller ,it
gives me error in DraggableViewBackground View . Now the thing i want to
ask is how can i create the cards tappable. help me i've working on this
from last day ,.

**Comment by cwRichardKim** [comment]
I'm really sorry, but the github issues section of this repository is meant for resolving issues with the repository.  I unfortunately can't afford to spend time with everyone's issues outside of the scope of this project
