### ISSUE TITLE
Incorrect behaviour in ios7 with constraints

### ISSUE THREAD

**Issue by Nebla** [cwRichardKim/TinderSimpleSwipeCards#6]
In ios 7, when the view is using autolayout with constaints, it only rotates and scales when doing pan, it seems that

self.center = CGPointMake(self.originalPoint.x + xFromCenter, self.originalPoint.y + yFromCenter);

isn't working properly in this case (in ios8 it works as expected). What I did to solve this is instead of changing the center property I changed the constraints values (I have four constraints in the view, one for each side), I couldn't figure out another solution. It would be something like this:

CGPoint translation = [gestureRecognizer translationInView:self.superview];

        case UIGestureRecognizerStateBegan:{
            self.originalPoint = self.center;
            
            originalTop = self.topSpace.constant;
            originalBottom = self.bottomSpace.constant;
            originalTrailling = self.trailingSpace.constant;
            originalLeading = self.leadingSpace.constant;
            
            break;
        };
        case UIGestureRecognizerStateChanged:{
            ... Stuff ...
            [self updatePositionWithDelta:translation];

- (void) updatePositionWithDelta:(CGPoint)delta {
    self.topSpace.constant = originalTop + delta.y;
    self.bottomSpace.constant = originalBottom - delta.y;

    self.leadingSpace.constant = originalLeading + delta.x;
    self.trailingSpace.constant = originalTrailling - delta.x;
    
    [self updateConstraintsIfNeeded];
}

Hope it helps.

**Comment by horsejockey** [comment]
hey @Nebla and @cwRichardKim I am having the same issue on iOS 7.  I don't fully understand the implementation your describing. what is the self.topSpace.constant referencing?  I am adding my constraitns in the DraggableViewController using constraintsWithVisualFormat. Thanks for any help.

**Comment by cwRichardKim** [comment]
Hey sorry for the late response.  Are you still having this issue?  I just tried to replicate it with iOS 7 and it's working fine for me.  Are you using a device or a simulator?

**Comment by horsejockey** [comment]
I was using a simulator.  I ended up deciding that I didnt need the rotation. I still like the look of swiping without rotation.  I may dig into it one day and try and figure it out.
