### ISSUE TITLE
Detect swipe up and swipe down

### ISSUE THREAD

**Issue by KCastiglione** [cwRichardKim/TinderSimpleSwipeCards#8]
It will be great to detect swipe up and down, and have delegates just like cardSwipedRight and left.

**Comment by cwRichardKim** [comment]
unfortunately, this is way harder to do than you'd think.  Right now i have a line dividing the screen in half, but with 4 cases, it's not as easy.  I'd be interested to see anyone implement this successfully though!

**Comment by KCastiglione** [comment]
Thanks for feedback, https://github.com/zhxnlai/ZLSwipeableView this has up and down and left and right, will be great if TinderSimpleSwipeCards has that too. Thanks for making this awesome library.
