### ISSUE TITLE
Hy Dear,

### ISSUE THREAD

**Issue by safyan** [cwRichardKim/TinderSimpleSwipeCards#9]
I am using this Demo in my App. i want to show most upper view with different cgrect so that lower view could be seeand  user can understand that it is swapable.
can you tell me how i can change this ?
same like this image . Lower views are also see able
![sample](https://cloud.githubusercontent.com/assets/6926766/6285302/f3ff1a32-b91b-11e4-88ff-0e35c255b740.png)

**Comment by cwRichardKim** [comment]
hmm, yea all you would have to do is have it so that when something is swiped to the right, it changes the cgrect of the object below it (which should be in the array loadedCards). You would also have to build it such that when you add a card to loaded cards, it has a different cgrect
